In [4]:
%matplotlib inline
from importlib import *
import numpy as np
from KMeans import k_means

reload(k_means)

data_mat = np.mat(k_means.load_data_set('Data/testSet.txt'))
my_cents, cluster_tab = k_means.k_means(data_mat, 4)

[[ 3.84322646 -1.4465141 ]
 [-3.98533571  4.72626688]
 [-1.76031334  4.80158477]
 [-0.48882163 -0.59875263]]
[[ 3.18732136 -1.17077828]
 [-3.48664243  2.77252571]
 [ 0.01289986  3.38919809]
 [-2.45574581 -2.32140327]]
[[ 2.96839327 -2.13784255]
 [-2.84017553  2.6309902 ]
 [ 1.6457145   3.370942  ]
 [-3.19984738 -2.96423548]]
[[ 2.80293085 -2.7315146 ]
 [-2.46154315  2.78737555]
 [ 2.6265299   3.10868015]
 [-3.38237045 -2.9473363 ]]


In [7]:
%matplotlib inline
from importlib import *
import numpy as np
from KMeans import k_means

reload(k_means)

dat_mat3 = np.mat(k_means.load_data_set('Data/testSet2.txt'))
cent_list, my_new_assignments = k_means.bi_k_means(dat_mat3, 3)

[[-0.1805513   3.56074465]
 [-4.810222   -0.42092459]]
[[ 0.18204313  3.32057745]
 [-0.74459109 -2.39373345]]
[[-0.00675605  3.22710297]
 [-0.45965615 -2.7782156 ]]
sse_split, and not_split:  453.0334895807502 0.0
the bestCentToSplit is:  0
the len of bestClustAss is:  60
[[2.60032704 3.08764007]
 [3.63985347 2.16150511]]
[[-0.79321379  3.40909973]
 [ 3.70083043  2.36911829]]
[[-2.56687932  3.32870355]
 [ 3.1222835   3.1029245 ]]
[[-2.94737575  3.3263781 ]
 [ 2.93386365  3.12782785]]
sse_split, and not_split:  77.59224931775066 29.15724944412535
the bestCentToSplit is:  0
the len of bestClustAss is:  40
[[-0.49621303 -3.3026406 ]
 [ 0.67240362 -1.89840992]]
[[-0.54562988 -2.99100569]
 [-0.11576125 -1.92705525]]
[[-0.39994281 -3.1000235 ]
 [-0.6985095  -1.490984  ]]
[[-0.15366667 -3.15354   ]
 [-1.3776246  -1.6522424 ]]
[[-0.05200457 -3.16610557]
 [-1.41084317 -1.873139  ]]
[[-7.11923077e-04 -3.21792031e+00]
 [-1.31198114e+00 -1.96162114e+00]]
[[ 0.07973025 -3.24942808]
 [-1.26873575 -2

In [8]:
cent_list

matrix([[-2.94737575,  3.3263781 ],
        [ 0.35496167, -3.36033556],
        [ 2.93386365,  3.12782785],
        [-1.12616164, -2.30193564]])

In [1]:
print('bad code')

bad code
