In [9]:
%matplotlib inline
from importlib import *
import numpy as np
from CART import cart

reload(cart)

test_mat = np.mat(np.eye(4))
mat0, mat1 = cart.bi_split_data_set(test_mat, 1, 0.5)
print(mat0, mat1)

[[0. 1. 0. 0.]] [[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
np.mat(np.eye(4))

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [26]:
%matplotlib inline
from importlib import *
import numpy as np
from CART import cart

reload(cart)

my_dat = cart.load_data_set('Data/ex00.txt')
my_mat = np.mat(my_dat)
cart.create_tree(my_mat)

{'sp_idx': 0,
 'sp_val': 0.48813,
 'left': 1.0180967672413792,
 'right': -0.04465028571428572}

In [27]:
my_dat1 = cart.load_data_set('Data/ex0.txt')
my_mat1 = np.mat(my_dat1)
cart.create_tree(my_mat1)

{'sp_idx': 1,
 'sp_val': 0.39435,
 'left': {'sp_idx': 1,
  'sp_val': 0.582002,
  'left': {'sp_idx': 1,
   'sp_val': 0.797583,
   'left': 3.9871632,
   'right': 2.9836209534883724},
  'right': 1.980035071428571},
 'right': {'sp_idx': 1,
  'sp_val': 0.197834,
  'left': 1.0289583666666666,
  'right': -0.023838155555555553}}

In [28]:
my_dat2 = cart.load_data_set('Data/ex2.txt')
my_mat2 = np.mat(my_dat2)
cart.create_tree(my_mat2)

{'sp_idx': 0,
 'sp_val': 0.499171,
 'left': {'sp_idx': 0,
  'sp_val': 0.729397,
  'left': {'sp_idx': 0,
   'sp_val': 0.952833,
   'left': {'sp_idx': 0,
    'sp_val': 0.958512,
    'left': 105.24862350000001,
    'right': 112.42895575000001},
   'right': {'sp_idx': 0,
    'sp_val': 0.759504,
    'left': {'sp_idx': 0,
     'sp_val': 0.790312,
     'left': {'sp_idx': 0,
      'sp_val': 0.833026,
      'left': {'sp_idx': 0,
       'sp_val': 0.944221,
       'left': 87.3103875,
       'right': {'sp_idx': 0,
        'sp_val': 0.85497,
        'left': {'sp_idx': 0,
         'sp_val': 0.910975,
         'left': 96.452867,
         'right': {'sp_idx': 0,
          'sp_val': 0.892999,
          'left': 104.825409,
          'right': {'sp_idx': 0,
           'sp_val': 0.872883,
           'left': 95.181793,
           'right': 102.25234449999999}}},
        'right': 95.27584316666666}},
      'right': {'sp_idx': 0,
       'sp_val': 0.811602,
       'left': 81.110152,
       'right': 88.7844988000

In [32]:
%matplotlib inline
from importlib import *
import numpy as np
from CART import cart

reload(cart)

my_tree = cart.create_tree(my_mat2, ops=(0, 1))
my_dat_test = cart.load_data_set('Data/ex2test.txt')
my_mat2_test = np.mat(my_dat_test)
new_tree = cart.prune(my_tree, my_mat2_test)

print(new_tree)

merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
{'sp_idx': 0, 'sp_val': 0.499171, 'left': {'sp_idx': 0, 'sp_val': 0.729397, 'left': {'sp_idx': 0, 'sp_val': 0.952833, 'left': {'sp_idx': 0, 'sp_val': 0.965969, 'left': 92.5239915, 'right': {'sp_idx': 0, 'sp_val': 0.956951, 'left': {'sp_idx': 0, 'sp_val': 0.958512, 'left': {'sp_idx': 0, 'sp_val': 0.960398, 'left': 112.386764, 'right': 123.559747}, 'right': 135.837013}, 'right': 111.2013225}}, 'right': {'sp_idx': 0, 'sp_val': 0.759504, 'left': {'sp_idx': 0, 'sp_val': 0.763328, 'left': {'sp_idx': 0, 'sp_val': 0.769043, 'left': {'sp_idx': 0, 'sp_val': 0.790312, 'left': {'sp_idx': 0, 'sp_val': 0.806158, 'left': {'sp_idx': 0, 'sp_val': 0.815215, 

In [34]:
%matplotlib inline
from importlib import *
import numpy as np
from CART import cart

reload(cart)

my_mat2 = np.mat(cart.load_data_set('Data/exp2.txt'))

cart.create_tree(my_mat2, cart.model_leaf, cart.model_err, (1, 10))

{'sp_idx': 0, 'sp_val': 0.285477, 'left': matrix([[1.69855694e-03],
         [1.19647739e+01]]), 'right': matrix([[3.46877936],
         [1.18521743]])}

In [39]:
%matplotlib inline
from importlib import *
import numpy as np
from CART import cart

reload(cart)

train_mat = np.mat(cart.load_data_set('Data/bikeSpeedVsIq_train.txt'))
test_mat = np.mat(cart.load_data_set('Data/bikeSpeedVsIq_test.txt'))

my_tree = cart.create_tree(train_mat, ops=(1, 20))
y_hat = cart.create_forecast(my_tree, test_mat[:, 0])
np.corrcoef(y_hat, test_mat[:, 1], rowvar=0)[0, 1]

0.9640852318222146

In [40]:
my_tree = cart.create_tree(train_mat, cart.model_leaf, cart.model_err, (1, 20))
y_hat = cart.create_forecast(my_tree, test_mat[:, 0], cart.model_tree_eval)
np.corrcoef(y_hat, test_mat[:, 1], rowvar=0)[0, 1]

0.9760412191380597

In [41]:
ws, x, y = cart.lin_solve(train_mat)
ws

matrix([[37.58916794],
        [ 6.18978355]])

In [42]:
for i in range(np.shape(test_mat)[0]):
    y_hat[i] = test_mat[i, 0] * ws[1, 0] + ws[0, 0]

np.corrcoef(y_hat, test_mat[:, 1], rowvar=0)[0, 1]

0.9434684235674762