In [1]:
import numpy as np

u, sigma, vt = np.linalg.svd([[1, 1], [7, 7]])
u

array([[-0.14142136, -0.98994949],
       [-0.98994949,  0.14142136]])

In [2]:
sigma

array([1.00000000e+01, 2.82797782e-16])

In [3]:
vt

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [9]:
import importlib
import numpy as np

import svd
importlib.reload(svd)

<module 'svd' from '/Users/rui/ML/scratch/SVD/svd.py'>

In [6]:
mat = np.mat(svd.load_data())
svd.euclid_sim(mat[:, 0], mat[:, 4])

0.13367660240019172

In [7]:
svd.cos_sim(mat[:, 0], mat[:, 4])

0.5472455591261534

In [8]:
svd.pears_sim(mat[:, 0], mat[:, 4])

0.23768619407595826

In [11]:
mat[0,1]=mat[0,0]=mat[1,0]=mat[2,0]=4
mat[3, 3] = 2
mat

matrix([[4, 4, 1, 0, 0],
        [4, 2, 2, 0, 0],
        [4, 1, 1, 0, 0],
        [5, 5, 5, 2, 0],
        [1, 1, 0, 2, 2],
        [0, 0, 0, 3, 3],
        [0, 0, 0, 1, 1]])

In [13]:
svd.recommend(mat, 3)

4 and 0 similarity is: 1.000000
4 and 1 similarity is: 1.000000
4 and 2 similarity is: 0.000000
4 and 3 similarity is: 1.000000


[(4, 4.0)]

In [3]:
import importlib
import numpy as np

import svd
importlib.reload(svd)

<module 'svd' from '/Users/rui/ML/scratch/SVD/svd.py'>

In [4]:
svd.img_compress(2)

*** original matrix ***
00000000000000110000000000000000
00000000000011111100000000000000
00000000000111111110000000000000
00000000001111111111000000000000
00000000111111111111100000000000
00000001111111111111110000000000
00000000111111111111111000000000
00000000111111100001111100000000
00000001111111000001111100000000
00000011111100000000111100000000
00000011111100000000111110000000
00000011111100000000011110000000
00000011111100000000011110000000
00000001111110000000001111000000
00000011111110000000001111000000
00000011111100000000001111000000
00000001111100000000001111000000
00000011111100000000001111000000
00000001111100000000001111000000
00000001111100000000011111000000
00000000111110000000001111100000
00000000111110000000001111100000
00000000111110000000001111100000
00000000111110000000011111000000
00000000111110000000111111000000
00000000111111000001111110000000
00000000011111111111111110000000
00000000001111111111111110000000
00000000001111111111111110000000
0000000000011111111